### ISSUE TITLE
MIT or Apache 2.0 open source license

### ISSUE THREAD

**Issue by jasonblais** [acornjs/acorn-stage3#2]
@adrianheine Thank you for sharing this project! 

We'd love to use it as part of the Mattermost open source project (https://www.mattermost.org/) in our [Web App](https://github.com/mattermost/mattermost-webapp), which uses an [Apache 2.0 license](https://github.com/mattermost/mattermost-webapp/blob/master/LICENSE.txt)). 

Would you be open to adding either an [MIT](https://opensource.org/licenses/MIT) or an [Apache 2.0](https://opensource.org/licenses/Apache-2.0) license to your project? 

If you use either an MIT license or an Apache 2.0 license it would make it easy to add your work to other open source projects, and we'd love to include your work in ours. 

Thanks kindly for your consideration.

**Comment by adrianheine** [comment]
0.7.0 is released under the MIT license.
